### ISSUE TITLE
Deattach Microphone from R5Stream object

### ISSUE THREAD

**Issue by aarajput** [red5pro/red5pro-android-app#31]
I was trying to deattach microphone from R5Stream object, but i didnt find any method.
I tried to pass null in R5Steam.attachMicrophone(R5Microphone microphone). But it didnt work.

**Comment by HoldenMills** [comment]
I would recommend just not attaching the R5Microphone at all. Just attach an R5VideoSource/R5Camera. Or is your question, that you are trying to remove the mic mid stream after it was already started? You may want to check out our testbed example which shows turning off audio: https://github.com/red5pro/android-streaming-testbed
https://github.com/red5pro/ios-streaming-testbed

**Comment by aarajput** [comment]
I want to add a feature of mute in application. 
I have tried "android-streaming-testbed", but there is not screen with mute button on it.

**Comment by aarajput** [comment]
Please!! Need help

**Comment by HoldenMills** [comment]
Sorry for the delay in getting back to you. Please use this example: https://github.com/red5pro/red5pro-android-app.  Under the "home" screen you can uncheck the audio button.

**Comment by aarajput** [comment]
Thanks for you cooperation Hoden.

Yes, there is a checkbox with audio.
But it is for if you want to start publishing audio without microphone.
What what i want is to remove microphone after publish has started.

**Comment by HoldenMills** [comment]
OK.  I understand you now.  That functionality is on our roadmap.  If you send me a support request at https://red5pro.zendesk.com/hc/en-us/requests/new I will make sure that you stay updated with our progress.

**Comment by aarajput** [comment]
Thanks alot. I will add support request.
There is an other issue i am facing.
If i have two objects of R5Steam, one is subscribe, and other one is publish, for two way communication.
If i stop publish using publish.stop(), then subscribe also stops receiving streams from other device.
The thing i want is subscribe should continue receiving streams from other device, even i have stopped publishing my audio from my device.

Can you please help me?
Thanks

**Comment by HoldenMills** [comment]
Hi.  Sorry for the delay in getting back to you.  Once you stop publishing you cannot subscribe to a stream that no longer exists.  What is your use case for this?  Maybe if you tell me your big picture goal I can help you implement it.

**Comment by aarajput** [comment]
Its ok and Thanks for helping me in my issues.
The issue i am facing is that if i have two devices A and B. A and B both are publishing audio.
Then device A subscribe to device B.
After some time, i call publish.stop() method in device A to stop publish. But when i call publish.stop() in device A, it also stop "subscrib" and i stop listening to audio of device B.
I thing i want is that device A should keep listening to device B, even device A has stop publish.

(note: Device B is always publishing)

**Comment by HoldenMills** [comment]
The way that our two-way example is written has two people subscribing and publishing to each other.  Thus A is both publishing to, and subscribing from B while B is doing the same to A.  If I understand you correctly, you are trying to go from A and B having a two-way conversation to just B publishing and A subscribing.  This is unique use-case that we have not seen before.  Please let me run this by the Support Team and I will let you know what we have to say.  
Lastly, you had originally asked about muting which is a feature that is potentially coming out in September.  It would probably be easier for you to wait on this, but I understand that you might be on a deadline.  Thanks.

**Comment by aarajput** [comment]
Thanks alot Holden. You have helped me alot. And please also add my last issue in support. Thanks

**Comment by HoldenMills** [comment]
Glad to help!  If it's not too much trouble, could please submit the issue using this link: [https://red5pro.zendesk.com/hc/en-us/requests/new](https://red5pro.zendesk.com/hc/en-us/requests/new).  That way it will be clear which issue you are talking about and if you fill out the fields on the support form I can have a better idea of how you have evrything set-up.  Thanks!
