### ISSUE TITLE
Find all live users on server.

### ISSUE THREAD

**Issue by aarajput** [red5pro/red5pro-android-app#32]
Hi!!
I am create a voice broadcast android application. I want to see list of all online users.
How i am gona do that?
I can't see any method in sdk to fulfil my purpose.
Thanks

**Comment by HoldenMills** [comment]
Hi.  I apologize for the very late response.  Using our REST API you can use the [getClients](https://www.red5pro.com/docs/server/serverapi/#getclients) call.  Please let me know if any of our documentation is unclear, or if I misunderstood your question.  Thanks!
