### ISSUE TITLE
Black screen after subscribing

### ISSUE THREAD

**Issue by tushar-bhatia** [red5pro/red5pro-android-app#37]
hey guyzz, m getting black screen after subscribing a stream..Toasts are showing up correctly saying "connected" followed by "started stream" but nothing shown up in R5VideoView. m running the server locally on windows 10.

**Comment by HoldenMills** [comment]
What devices are you using to publish and subscribe?  We have fixed an issue with Android Marshmallow devices and will release the fix with our next update coming out soon.

**Comment by DKKovalev** [comment]
Hi. I'm having the same issue. I'm running stream locally from localhost:5080 and it seems that i connected successfully, but i nothing shown, except sound. I'm using Oneplus One with Android 6.0.1

**Comment by tushar-bhatia** [comment]
red% pro sucksssss

**Comment by HoldenMills** [comment]
We hope to launch an SDK update soon which will fix this blank screen bug.

**Comment by beetlejesss** [comment]
SDK 1.4.0, which is included in the latest checkin, should address this issue
